apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlabRunner
  labels:
    app: gitlabRunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlabRunner
  template:
    metadata:
      labels:
        app: gitlabRunner
    spec:
      containers:
      - name: gitlabRunner
        image: ahhatem/gitlabRunner
        ports:
            - containerPort: 22 
        env:
            - name: gitlabToken
              value: "5000"
            - name: gitlabURL
              value: http://gitlab-lb:80

---

apiVersion: v1
kind: Service
metadata:
  name: gitlabRunner-service
  labels:
    app: gitlabRunner
spec:
  ports:
  - name: tcp
    port: 22
    protocol: TCP
  selector:
    app: gitlabRunner
  type: NodePort